### ISSUE TITLE
App crashing when dispose midi pro

### ISSUE THREAD

**Issue by Snoobdog10x** [melihhakanpektas/flutter_midi_pro#13]
Hi dev, your package is good, but when i dispose and reinit midi player, its crash app on android, and ios cannot play any sound.
Here is the log:
```
I/_piano_keyboard( 5344): Starting a blocking GC Alloc
I/_piano_keyboard( 5344): Waiting for a blocking GC Alloc
I/_piano_keyboard( 5344): Clamp target GC heap from 215MB to 192MB
I/_piano_keyboard( 5344): Background concurrent mark compact GC freed 96KB AllocSpace bytes, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 56us,1.600ms total 131.694ms
I/_piano_keyboard( 5344): WaitForGcToComplete blocked Alloc on Background for 131.573ms
I/_piano_keyboard( 5344): Starting a blocking GC Alloc
I/_piano_keyboard( 5344): Waiting for a blocking GC Alloc
I/_piano_keyboard( 5344): Clamp target GC heap from 215MB to 192MB
I/_piano_keyboard( 5344): Background concurrent mark compact GC freed 88KB AllocSpace bytes, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 57us,1.061ms total 130.486ms
I/_piano_keyboard( 5344): WaitForGcToComplete blocked Alloc on Background for 130.190ms
I/_piano_keyboard( 5344): Starting a blocking GC Alloc
I/_piano_keyboard( 5344): Waiting for a blocking GC Alloc
I/_piano_keyboard( 5344): Clamp target GC heap from 215MB to 192MB
I/_piano_keyboard( 5344): Background concurrent mark compact GC freed 92KB AllocSpace bytes, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 72us,1.056ms total 132.666ms
I/_piano_keyboard( 5344): WaitForGcToComplete blocked Alloc on Background for 132.412ms
I/_piano_keyboard( 5344): Starting a blocking GC Alloc
I/_piano_keyboard( 5344): Waiting for a blocking GC Alloc
I/_piano_keyboard( 5344): Clamp target GC heap from 215MB to 192MB
I/_piano_keyboard( 5344): Background concurrent mark compact GC freed 88KB AllocSpace bytes, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 61us,889us total 128.827ms
I/_piano_keyboard( 5344): WaitForGcToComplete blocked Alloc on Background for 128.578ms
I/_piano_keyboard( 5344): Starting a blocking GC Alloc
I/_piano_keyboard( 5344): Waiting for a blocking GC Alloc
I/_piano_keyboard( 5344): Clamp target GC heap from 215MB to 192MB
I/_piano_keyboard( 5344): Background concurrent mark compact GC freed 96KB AllocSpace bytes, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 60us,1.226ms total 135.259ms
I/_piano_keyboard( 5344): WaitForGcToComplete blocked Alloc on Background for 135.183ms
I/_piano_keyboard( 5344): Starting a blocking GC Alloc
I/_piano_keyboard( 5344): Waiting for a blocking GC Alloc
I/_piano_keyboard( 5344): Clamp target GC heap from 215MB to 192MB
I/_piano_keyboard( 5344): Background concurrent mark compact GC freed 88KB AllocSpace bytes, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 57us,935us total 131.057ms
I/_piano_keyboard( 5344): WaitForGcToComplete blocked Alloc on Background for 130.664ms
I/_piano_keyboard( 5344): Starting a blocking GC Alloc
I/_piano_keyboard( 5344): Waiting for a blocking GC Alloc
I/_piano_keyboard( 5344): Clamp target GC heap from 215MB to 192MB
I/_piano_keyboard( 5344): Background concurrent mark compact GC freed 60KB AllocSpace bytes, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 57us,1.088ms total 138.993ms
I/_piano_keyboard( 5344): WaitForGcToComplete blocked Alloc on Background for 138.801ms
I/_piano_keyboard( 5344): Starting a blocking GC Alloc
I/_piano_keyboard( 5344): Waiting for a blocking GC Alloc
I/_piano_keyboard( 5344): Clamp target GC heap from 215MB to 192MB
I/_piano_keyboard( 5344): Background concurrent mark compact GC freed 60KB AllocSpace bytes, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 57us,938us total 130.978ms
I/_piano_keyboard( 5344): WaitForGcToComplete blocked Alloc on Background for 130.856ms
I/_piano_keyboard( 5344): Starting a blocking GC Alloc
I/_piano_keyboard( 5344): Waiting for a blocking GC Alloc
I/_piano_keyboard( 5344): Clamp target GC heap from 215MB to 192MB
I/_piano_keyboard( 5344): Background concurrent mark compact GC freed 64KB AllocSpace bytes, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 56us,899us total 133.206ms
I/_piano_keyboard( 5344): WaitForGcToComplete blocked Alloc on Background for 133.124ms
I/_piano_keyboard( 5344): Starting a blocking GC Alloc
I/_piano_keyboard( 5344): Waiting for a blocking GC Alloc
I/_piano_keyboard( 5344): Clamp target GC heap from 215MB to 192MB
I/_piano_keyboard( 5344): Background concurrent mark compact GC freed 60KB AllocSpace bytes, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 58us,925us total 132.594ms
I/_piano_keyboard( 5344): WaitForGcToComplete blocked Alloc on Background for 132.142ms
I/_piano_keyboard( 5344): Starting a blocking GC Alloc
I/_piano_keyboard( 5344): Starting a blocking GC Alloc
I/_piano_keyboard( 5344): Starting a blocking GC Alloc
I/_piano_keyboard( 5344): Clamp target GC heap from 215MB to 192MB
I/_piano_keyboard( 5344): Alloc concurrent mark compact GC freed 64KB AllocSpace bytes, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 58us,862us total 133.740ms
I/_piano_keyboard( 5344): Forcing collection of SoftReferences for 32B allocation
I/_piano_keyboard( 5344): Starting a blocking GC Alloc
I/_piano_keyboard( 5344): Clamp target GC heap from 215MB to 192MB
I/_piano_keyboard( 5344): Alloc concurrent mark compact GC freed 32KB AllocSpace bytes, 0(0B) LOS objects, 0% free, 191MB/192MB, paused 63us,1.110ms total 137.553ms
I/_piano_keyboard( 5344): WaitForGcToComplete blocked Background on Alloc for 271.169ms
W/_piano_keyboard( 5344): Throwing OutOfMemoryError "Failed to allocate a 32 byte allocation with 78192 free bytes and 76KB until OOM, target footprint 201326592, growth limit 201326592; giving up on allocation because <1% of heap free after GC." (VmSize 21366200 kB)
I/_piano_keyboard( 5344): Waiting for a blocking GC Alloc
I/_piano_keyboard( 5344): Clamp target GC heap from 212MB to 192MB
I/_piano_keyboard( 5344): Background concurrent mark compact GC freed 3224KB AllocSpace bytes, 0(0B) LOS objects, 1% free, 188MB/192MB, paused 55us,1.135ms total 133.909ms
I/_piano_keyboard( 5344): WaitForGcToComplete blocked Alloc on Background for 129.675ms
I/_piano_keyboard( 5344): Starting a blocking GC Alloc
W/_piano_keyboard( 5344): Verification of kotlin.sequences.Sequence kotlin.sequences.SequencesKt___SequencesKt.runningReduce(kotlin.sequences.Sequence, kotlin.jvm.functions.Function2) took 129.734ms (177.29 bytecodes/s) (2680B approximate peak alloc)
E/AndroidRuntime( 5344): FATAL EXCEPTION: DefaultDispatcher-worker-3
E/AndroidRuntime( 5344): Process: com.example.a12_piano_keyboard, PID: 5344
E/AndroidRuntime( 5344): java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 78192 free bytes and 76KB until OOM, target footprint 201326592, growth limit 201326592; giving up on allocation because <1% of heap free after GC.
E/AndroidRuntime( 5344): 	at java.lang.StringFactory.newStringFromBytes(Native Method)
E/AndroidRuntime( 5344): 	at java.lang.StringLatin1.newString(StringLatin1.java:738)
E/AndroidRuntime( 5344): 	at java.lang.StringBuilder.toString(StringBuilder.java:474)
E/AndroidRuntime( 5344): 	at com.melihhakanpektas.midisynthesizer.sound.ModelIdentifier.toString(ModelIdentifier.java:166)
E/AndroidRuntime( 5344): 	at java.lang.String.valueOf(String.java:4102)
E/AndroidRuntime( 5344): 	at java.lang.StringBuffer.append(StringBuffer.java:308)
E/AndroidRuntime( 5344): 	at com.melihhakanpektas.midisynthesizer.sound.SoftPerformer.extractKeys(SoftPerformer.java:338)
E/AndroidRuntime( 5344): 	at com.melihhakanpektas.midisynthesizer.sound.SoftPerformer.<init>(SoftPerformer.java:684)
E/AndroidRuntime( 5344): 	at com.melihhakanpektas.midisynthesizer.sound.SoftInstrument.initPerformers(SoftInstrument.java:63)
E/AndroidRuntime( 5344): 	at com.melihhakanpektas.midisynthesizer.sound.SoftInstrument.<init>(SoftInstrument.java:47)
E/AndroidRuntime( 5344): 	at com.melihhakanpektas.midisynthesizer.sound.SoftSynthesizer.loadInstruments(SoftSynthesizer.java:295)
E/AndroidRuntime( 5344): 	at com.melihhakanpektas.midisynthesizer.sound.SoftSynthesizer.loadAllInstruments(SoftSynthesizer.java:792)
E/AndroidRuntime( 5344): 	at com.melihhakanpektas.flutter_midi_pro.FlutterMidiProPlugin$onMethodCall$1.invokeSuspend(FlutterMidiProPlugin.kt:43)
E/AndroidRuntime( 5344): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime( 5344): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/AndroidRuntime( 5344): 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
E/AndroidRuntime( 5344): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
E/AndroidRuntime( 5344): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
E/AndroidRuntime( 5344): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
E/AndroidRuntime( 5344): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
E/AndroidRuntime( 5344): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
E/AndroidRuntime( 5344): 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a0d0132, Dispatchers.IO]
I/Process ( 5344): Sending signal. PID: 5344 SIG: 9
```

**Comment by Snoobdog10x** [comment]
here is my code `import 'dart:async';

import 'package:flutter_midi_pro/flutter_midi_pro.dart';
import 'package:get/get.dart';

import '../utils/sound_data_utils.dart';
import 'setting_service.dart';

class SoundPoolPlayerService extends GetxService {
  final RxBool loading = true.obs;
  final MidiPro _midiPro = MidiPro();
  final Map<int, Timer> _stopTimer = {};

  @override
  Future<void> onInit() async {
    var settingService = Get.find<SettingService>();
    settingService.soundFontType.listen(_initSoundFont);
    await _initSoundFont(settingService.getSoundFont());
    super.onInit();
  }

  Future<void> _initSoundFont(String soundFont) async {
    loading.value = true;
    var soundFontAsset = SoundDataUtils.getSoundFontAsset(
      Get.find<SettingService>().getSoundFont(),
    );
    await _midiPro.loadSoundfont(sf2Path: soundFontAsset);
    await _midiPro.loadInstrument(instrumentIndex: 0);
    loading.value = false;
  }

  Future<void> playSound(int keyId) async {
    if (loading.value) {
      return;
    }

    _removeTimer(keyId);
    await _midiPro.playMidiNote(midi: keyId, velocity: 127);
  }

  void _removeTimer(int keyId) {
    _stopTimer[keyId]?.cancel();
    _stopTimer.remove(keyId);
  }

  Future<void> stopSound(
    int keyId, {
    Duration delay = const Duration(
      milliseconds: 600,
    ),
    void Function()? callback,
  }) async {
    if (loading.value) {
      return;
    }

    _stopTimer[keyId] = Timer(delay, () async {
      await _midiPro.stopMidiNote(midi: keyId, velocity: 127);
      _removeTimer(keyId);
      callback?.call();
    });
  }

  @override
  void onClose() {
    _midiPro.dispose();
    _stopTimer.forEach((key, value) {
      value.cancel();
    });
    _stopTimer.clear();
    super.onClose();
  }
}
`

**Comment by Snoobdog10x** [comment]
Here is my code
```
import 'dart:async';

import 'package:flutter_midi_pro/flutter_midi_pro.dart';
import 'package:get/get.dart';

import '../utils/sound_data_utils.dart';
import 'setting_service.dart';

class SoundPoolPlayerService extends GetxService {
  final RxBool loading = true.obs;
  final MidiPro _midiPro = MidiPro();
  final Map<int, Timer> _stopTimer = {};

  @override
  Future<void> onInit() async {
    var settingService = Get.find<SettingService>();
    settingService.soundFontType.listen(_initSoundFont);
    await _initSoundFont(settingService.getSoundFont());
    super.onInit();
  }

  Future<void> _initSoundFont(String soundFont) async {
    loading.value = true;
    var soundFontAsset = SoundDataUtils.getSoundFontAsset(
      Get.find<SettingService>().getSoundFont(),
    );
    await _midiPro.loadSoundfont(sf2Path: soundFontAsset);
    await _midiPro.loadInstrument(instrumentIndex: 0);
    loading.value = false;
  }

  Future<void> playSound(int keyId) async {
    if (loading.value) {
      return;
    }

    _removeTimer(keyId);
    await _midiPro.playMidiNote(midi: keyId, velocity: 127);
  }

  void _removeTimer(int keyId) {
    _stopTimer[keyId]?.cancel();
    _stopTimer.remove(keyId);
  }

  Future<void> stopSound(
    int keyId, {
    Duration delay = const Duration(
      milliseconds: 600,
    ),
    void Function()? callback,
  }) async {
    if (loading.value) {
      return;
    }

    _stopTimer[keyId] = Timer(delay, () async {
      await _midiPro.stopMidiNote(midi: keyId, velocity: 127);
      _removeTimer(keyId);
      callback?.call();
    });
  }

  @override
  void onClose() {
    _midiPro.dispose();
    _stopTimer.forEach((key, value) {
      value.cancel();
    });
    _stopTimer.clear();
    super.onClose();
  }
}
```

**Comment by KapitanPL** [comment]
From AudioSynthethiser.java

<p>Note that some synthesizers, once closed, cannot be reopened.
     * Attempts to reopen such a synthesizer will always result in
     * a <code>MidiUnavailableException</code>.
     
     On method "Open"

**Comment by melihhakanpektas** [comment]
Android method has been completely changed.

**Comment by thanhbao0408** [comment]
I have the same issue. On Android it crashes when dispose and re-initialize. Remove the dispose function fix the crashing.
