### ISSUE TITLE
[Bug] Crashes when switching focus to the application

### ISSUE THREAD

**Issue by kurenai-11** [melihhakanpektas/flutter_midi_pro#4]
When you hide the app, then reopen it (like alt tabbing on pc, I don't know what it's called on android), the app crashes.
May be related to #1 because the error is also an out of memory error.
Device: Redmi Note 12
OS: Android 13
Crash log:
```
D/DecorView[](24986): onWindowFocusChanged hasWindowFocus true
I/HandWritingStubImpl(24986): refreshLastKeyboardType: 1
I/HandWritingStubImpl(24986): getCurrentKeyboardType: 1
D/AudioTrack(24986): set(sessionId=0), mcallback is 1
D/AudioTrack(24986): set(): streamType -1, sampleRate 44100, format 0x1, channelMask 0x3, frameCount 5292, flags #0, notificationFrames 0, sessionId 0, transferType 3, uid -1, pid -1
I/ect_ear_trainer(24986): Clamp target GC heap from 265MB to 256MB
W/AudioTrack(24986): Use of stream types is deprecated for operations other than volume control
W/AudioTrack(24986): See the documentation of AudioTrack() for what to use instead with android.media.AudioAttributes to qualify your playback use case
D/AudioTrack(24986): start(6086): prior state:STATE_STOPPED
I/ect_ear_trainer(24986): Waiting for a blocking GC Alloc
I/ect_ear_trainer(24986): Waiting for a blocking GC Alloc
I/ect_ear_trainer(24986): WaitForGcToComplete blocked Alloc on Background for 15.227ms
I/ect_ear_trainer(24986): Starting a blocking GC Alloc
I/ect_ear_trainer(24986): WaitForGcToComplete blocked Alloc on Background for 10.424ms
I/ect_ear_trainer(24986): Starting a blocking GC Alloc
I/ect_ear_trainer(24986): Starting a blocking GC Alloc
I/ect_ear_trainer(24986): Starting a blocking GC Alloc
I/ect_ear_trainer(24986): Alloc young concurrent copying GC freed 220458(5242KB) AllocSpace objects, 0(0B) LOS objects, 2% free, 249MB/256MB, paused 41us,21us total 20.054ms
I/ect_ear_trainer(24986): Starting a blocking GC Alloc
I/ect_ear_trainer(24986): Starting a blocking GC Alloc
I/ect_ear_trainer(24986): Alloc young concurrent copying GC freed 7(31KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 255MB/256MB, paused 53us,20us total 30.335ms
I/ect_ear_trainer(24986): Forcing collection of SoftReferences for 2337KB allocation
I/ect_ear_trainer(24986): Starting a blocking GC Alloc
W/ect_ear_trainer(24986): Cleared Reference was only reachable from finalizer (only reported once)
I/ect_ear_trainer(24986): Clamp target GC heap from 276MB to 256MB
I/ect_ear_trainer(24986): Alloc concurrent copying GC freed 136572(2862KB) AllocSpace objects, 0(0B) LOS objects, 1% free, 252MB/256MB, paused 24us,23us total 223.871ms
I/ect_ear_trainer(24986): Starting a blocking GC Alloc
I/ect_ear_trainer(24986): Starting a blocking GC Alloc
I/ect_ear_trainer(24986): Alloc young concurrent copying GC freed 34(31KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 254MB/256MB, paused 44us,29us total 5.902ms
I/ect_ear_trainer(24986): Forcing collection of SoftReferences for 2118KB allocation
I/ect_ear_trainer(24986): Starting a blocking GC Alloc
I/ect_ear_trainer(24986): Clamp target GC heap from 278MB to 256MB
I/ect_ear_trainer(24986): Alloc concurrent copying GC freed 1430(92KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 254MB/256MB, paused 44us,33us total 223.482ms
W/ect_ear_trainer(24986): Throwing OutOfMemoryError "Failed to allocate a 2169068 byte allocation with 1551672 free bytes and 1515KB until OOM, target footprint 268435456, growth limit 268435456" (VmSize 12510676 kB)
I/ect_ear_trainer(24986): Starting a blocking GC Alloc
I/ect_ear_trainer(24986): Starting a blocking GC Alloc
I/ect_ear_trainer(24986): Forcing collection of SoftReferences for 2118KB allocation
I/ect_ear_trainer(24986): Starting a blocking GC Alloc
I/ect_ear_trainer(24986): Clamp target GC heap from 278MB to 256MB
I/ect_ear_trainer(24986): Alloc concurrent copying GC freed 96(34KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 254MB/256MB, paused 25us,32us total 221.748ms
W/ect_ear_trainer(24986): Throwing OutOfMemoryError "Failed to allocate a 2169072 byte allocation with 1554320 free bytes and 1517KB until OOM, target footprint 268435456, growth limit 268435456" (VmSize 12510676 kB)
E/AndroidRuntime(24986): FATAL EXCEPTION: main
E/AndroidRuntime(24986): Process: com.example.perfect_ear_trainer, PID: 24986
E/AndroidRuntime(24986): java.lang.OutOfMemoryError: Failed to allocate a 2169072 byte allocation with 1554320 free bytes and 1517KB until OOM, target footprint 268435456, growth limit 268435456
E/AndroidRuntime(24986):        at cn.sherlock.com.sun.media.sound.ModelByteBuffer.loadAll(ModelByteBuffer.java:274)
E/AndroidRuntime(24986):        at cn.sherlock.com.sun.media.sound.SoftSynthesizer.loadSamples(SoftSynthesizer.java:264)
E/AndroidRuntime(24986):        at cn.sherlock.com.sun.media.sound.SoftSynthesizer.loadInstruments(SoftSynthesizer.java:274)
E/AndroidRuntime(24986):        at cn.sherlock.com.sun.media.sound.SoftSynthesizer.loadAllInstruments(SoftSynthesizer.java:654)
E/AndroidRuntime(24986):        at com.melihhakanpektas.flutter_midi_pro.FlutterMidiProPlugin.onMethodCall(FlutterMidiProPlugin.kt:44)
E/AndroidRuntime(24986):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/AndroidRuntime(24986):        at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime(24986):        at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/AndroidRuntime(24986):        at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime(24986):        at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(24986):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(24986):        at android.os.Looper.loopOnce(Looper.java:211)
E/AndroidRuntime(24986):        at android.os.Looper.loop(Looper.java:300)
E/AndroidRuntime(24986):        at android.app.ActivityThread.main(ActivityThread.java:8395)
E/AndroidRuntime(24986):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24986):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
E/AndroidRuntime(24986):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
W/OOMEventManagerFK(24986): Failed to mkdir /data/miuilog/stability/memleak/heapdump/
I/Process (24986): Process is going to kill itself!
I/Process (24986): java.lang.Exception
I/Process (24986):      at android.os.Process.killProcess(Process.java:1344)
I/Process (24986):      at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:181)
I/Process (24986):      at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
I/Process (24986):      at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
I/Process (24986):      at io.flutter.embedding.engine.dart.DartMessenger.handleError(DartMessenger.java:419)
I/Process (24986):      at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:300)
I/Process (24986):      at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
I/Process (24986):      at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
I/Process (24986):      at android.os.Handler.handleCallback(Handler.java:942)
I/Process (24986):      at android.os.Handler.dispatchMessage(Handler.java:99)
I/Process (24986):      at android.os.Looper.loopOnce(Looper.java:211)
I/Process (24986):      at android.os.Looper.loop(Looper.java:300)
I/Process (24986):      at android.app.ActivityThread.main(ActivityThread.java:8395)
I/Process (24986):      at java.lang.reflect.Method.invoke(Native Method)
I/Process (24986):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
I/Process (24986):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
I/Process (24986): Sending signal. PID: 24986 SIG: 9
Lost connection to device.
```

**Comment by melihhakanpektas** [comment]
This package more stable now.
